-- 사용자 테이블
CREATE TABLE USERS(
  ID VARCHAR(20) NOT NULL PRIMARY KEY,
  UNAME VARCHAR(20) NOT NULL,
  POINT INT DEFAULT 0,
  PHONE VARCHAR(20)
);

-- 테이블의 구조를 확인할  수 있음
DESC USERS; 

-- 메세지 테이블
CREATE TABLE MESSAGES(
  MID INT NOT NULL PRIMARY KEY,
  SENDER VARCHAR(20)NOT NULL,
  RECEIVER VARCHAR(20) NOT NULL,
  SDATE DATE DEFAULT SYSDATE,
  MESSAGE VARCHAR(1000) NOT NULL,
  FOREIGN KEY(SENDER) REFERENCES USERS(ID),
  FOREIGN KEY(RECEIVER) REFERENCES USERS(ID)
);
DROP TABLE MESSAGES;

-- 사용자 입력(샘플데이터)
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('blue', '이블루', 20, '010-1010-1010');
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('red', '박레드', 10, '010-1010-2020');
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('green', '최그린', 10, '010-1010-3030');

SELECT * FROM USERS;
DELETE FROM USERS;

-- 메세지번호 시퀀스생성
CREATE SEQUENCE SEQ_MID START WITH 1 INCREMENT BY 1;

-- 메세지입력
INSERT INTO MESSAGES(MID, SENDER, RECEIVER, SDATE, MESSAGE)
VALUES(SEQ_MID.NEXTVAL, 'blue', 'red', SYSDATE, '레드야 잘지내지?');
INSERT INTO MESSAGES(MID, SENDER, RECEIVER, SDATE, MESSAGE)
VALUES(SEQ_MID.NEXTVAL, 'red', 'blue', SYSDATE, '블루야 오랜만이야!');
INSERT INTO MESSAGES(MID, SENDER, RECEIVER, SDATE, MESSAGE)
VALUES(SEQ_MID.NEXTVAL, 'green', 'blue', SYSDATE, '폭우 조심해!');
INSERT INTO MESSAGES(MID, SENDER, RECEIVER, SDATE, MESSAGE)
VALUES(SEQ_MID.NEXTVAL, 'blue', 'green', SYSDATE, '고마워 조심할게!');

SELECT * FROM MESSAGES;

--블루가 보낸 메세지
SELECT * FROM MESSAGES WHERE SENDER='blue';

SELECT  M.*, U.UNAME
FROM MESSAGES M, USERS U
WHERE SENDER='blue' AND U.ID=M.RECEIVER;

-- 블루가 받은 메세지
SELECT M.*, UNAME, PHONE -- 두 개의 테이블을 조인하는데, 이름이 다르면 하나는 안 써도 됨
FROM MESSAGES M, USERS U
WHERE RECEIVER='blue' AND SENDER=ID;

COMMIT;

--테이블 변경
ALTER TABLE MESSAGES ADD SDEL INT DEFAULT 0;
ALTER TABLE MESSAGES ADD RDEL INT DEFAULT 0;

SELECT * FROM MESSAGES;